### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by alimgafar** [guncebektas/autocms#2]
The example site is down, and I don't see any activity for more than a year. I'm investigating available Meteor CMS's for a project and was hoping to evaluate this one.

**Comment by guncebektas** [comment]
yes, it's still active and i'm using it in two apps. There isn't any bug in it. I have already added new features for my private use, will upload them in future. @alimgafar

**Comment by alimgafar** [comment]
Thanks. Will download to evaluate. When you get a chance, could you post what enhancements you're planning to add?
